.branches:
  # all branches
  only:
  - gh-pages
  - /.*/

matrix:
  include:
    - language: rust
      rust:
        - stable
      script:
        - echo "---- Rust Runtime -> Test & Build ----";
        - cd runtime-rust; cargo test --verbose --workspace;
        #- cargo build --verbose --workspace; cd ..;
        #- echo "---- Rust Validator -> Test & Build ----";
        #- cd validator-rust; cargo test --verbose --workspace;
        #- cargo build --verbose --workspace; cd ..;
      after_success:
        - echo "---- Rust Steps Complete ----"
