.branches:
  # all branches
  only:
  - gh-pages
  - /.*/

language: rust

rust:
  - stable

before_install:
  - # nothing yet

script:
  # Build the Rust runtime & run tests
  - cd runtime-rust; cargo build --verbose --all;
  - cargo test; cd..;
  - # Build the Rust validator
  - #cd validator-rust; cargo build --verbose --all; cd ..

after_success:
  - echo $TRAVIS_BRANCH;
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    echo "Build some docs!"
    fi
#  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
#    docker build -t tworavens/ravens-main:latest .;
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push tworavens/ravens-main:latest;
#    fi
