.branches:
  # all branches
  only:
  - gh-pages
  - /.*/

language: rust

rust:
  - stable

before_install:
  - sudo apt update
  - sudo apt install software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - sudo apt install python3.7
  # - sudo apt update
  - sudo python3 --version
  - sudo apt install python3-pip


script:
  # pytest
  - python --version
  - cd bindings-python; python3 hello.py; cd ..;
  # (1) Rust Runtime -> Test & Build
  #- cd runtime-rust; cargo test --verbose --workspace;
  #- cargo build --verbose --workspace; cd ..;
  # (2) Rust Validator -> Test & Build
  #- cd validator-rust; cargo test --verbose --workspace;
  #- cargo build --verbose --workspace; cd ..;

after_success:
  # Do some stuff
