dist: bionic

.branches:
  # all branches
  only:
  - gh-pages
  - /.*/

language: rust

rust:
  - stable

before_install:
  # Update to install python 3.6
  #   > Commented out for now.  It works but takes a while to run...
  #- sudo apt update
  #- sudo apt install -y software-properties-common
  #- sudo apt install -y python3-pip
  #- python3 --version

script:
  # (1) Rust Runtime -> Test & Build
  - cd runtime-rust; cargo test --verbose --workspace;
  - cargo build --verbose --workspace; cd ..;
  # (2) Rust Validator -> Test & Build
  - cd validator-rust; cargo test --verbose --workspace;
  - cargo build --verbose --workspace; cd ..;
  # (3) Build python bindings and run tests
  #   > Commented out for now.  It works but takes a while to run...
  #- cd bindings-python; python3 -m pip install -r requirements.txt;
  #- export RUST_BACKTRACE=1; python3 -m pip install -e . -v;
  #- python3 -m pytest -x -v; cd ..;

after_success:
  # Do some stuff
