.branches:
  # all branches
  only:
  - gh-pages
  - /.*/

language: rust

rust:
  - stable

before_install:
  - # nothing yet

script:
  - # Build the Rust runtime
  - # cd runtime-rust; cargo build --verbose --all; cd ..
  - # Build the Rust validator
  - cd validator-rust; cargo build --verbose --all; cd ..
