.branches:
  # all branches
  only:
  - gh-pages
  - /.*/

language: rust

rust:
  - stable

before_install:
  - sudo apt-get update
  - sudo apt-get install python3.6


script:
  # pytest
  - python --version
  - cd bindings-python; python3 hello.py; cd ..;
  # (1) Rust Runtime -> Test & Build
  #- cd runtime-rust; cargo test --verbose --workspace;
  #- cargo build --verbose --workspace; cd ..;
  # (2) Rust Validator -> Test & Build
  #- cd validator-rust; cargo test --verbose --workspace;
  #- cargo build --verbose --workspace; cd ..;

after_success:
  # Do some stuff
