dist: bionic

.branches:
  # all branches
  only:
  - gh-pages
  - /.*/

language: rust

rust:
  - stable

before_install:
  # Update to install python 3.6.9
  - sudo apt update
  - sudo apt install -y software-properties-common && python3-pip
  - python3 --version


script:
  # pytest
  - cd bindings-python; python3 -m pip install -r requirements.txt;
  - ./debug_ubuntu.sh; cd ..;
  # (1) Rust Runtime -> Test & Build
  #- cd runtime-rust; cargo test --verbose --workspace;
  #- cargo build --verbose --workspace; cd ..;
  # (2) Rust Validator -> Test & Build
  #- cd validator-rust; cargo test --verbose --workspace;
  #- cargo build --verbose --workspace; cd ..;

after_success:
  # Do some stuff
