name:                validator-haskell
version:             0.1.0.0
github:              "privacytoolsproject/DP-Proposal"
license:             BSD3
author:              "privacytoolsproject"
#maintainer:          ""
#copyright:           "2019 privacytoolsproject"

description:         Validator for differential privacy analyses

build-type: Custom
extra-source-files:
- ../prototypes/**/*.proto
- README.md

dependencies:
- base >= 4.7 && < 5

# contents to inject directly to .cabal file
# (library block could be translated to hpack)
verbatim: |

  custom-setup
    setup-depends:        base, Cabal, proto-lens-setup

  library
    default-language: Haskell2010
    c-sources: csrc/DPValidatorWrapper.c
    hs-source-dirs:
      src
    exposed-modules:
      Validator
      Proto.Analysis
      Proto.Analysis_Fields
      Proto.Release
      Proto.Release_Fields
      Proto.Types
      Proto.Types_Fields
    build-depends:
      base >=4.11 && <4.13
      , microlens
      , proto-lens
      , proto-lens-runtime
    ghc-options:
      -Wall -fwarn-unused-imports

  foreign-library Validator
    type:                native-shared
    lib-version-info:    6:3:2

    if os(Windows)
      options: standalone
      mod-def-file: DPValidator.def

    build-depends:
        validator-haskell
        , base >=4.11 && <4.13
        , microlens
        , proto-lens
        , proto-lens-runtime
    default-language:    Haskell2010
    hs-source-dirs:      src
    c-sources:           csrc/DPValidatorWrapper.c