[package]
name = "differential_privacy_runtime_rust"
version = "0.1.0"
authors = ["Shoeboxam <shoeboxam@gmail.com>"]
edition = "2018"

[dependencies]
prost = "0.5.0"
bytes = "0.4.12"
libc = "0.2"

[build-dependencies]
prost-build = { version = "0.5.0" }

[lib]
name = "differential_privacy_runtime_rust"
crate-type = ["dylib"]
