[package]
name = "differential_privacy_runtime_rust"
version = "0.1.0"
authors = ["Shoeboxam <shoeboxam@gmail.com>"]
edition = "2018"

[dependencies]
prost = "0.5.0"
bytes = "0.4.12"
libc = "0.2"
#ndarray = "0.13.0"
openssl = "0.10.25"
arrow = "0.15.0"
ffi-support = {version = "0.3.5"}

[build-dependencies]
prost-build = { version = "0.5.0" }

[lib]
name = "differential_privacy_runtime_rust"
crate-type = ["dylib"]

[profile.release]
debug = true